Update spkg
+- Refactored a lot of the code, primarily to add debugging / verbosity

diff --git a/spkg_plus/spkg b/spkg_plus/spkg
--- a/spkg_plus/spkg
+++ b/spkg_plus/spkg
@@ -1,16 +1,15 @@
 #!/bin/bash
 set -e
 
-REPOS=("https://lfs.gnlug.org/pub/lfs/lfs-packages/12.4/")
+REPOS=()
 REPO_LIST="REPO_LIST.txt"
-PKG_DIR="./sources/"
-TIME_OUT="10" # 10 second connection timout 
-MAX_TIMEOUT="300" # 5 minute timeout
-SUCCESS_URLS=() # Array of urls that connected successfully
+PKG_DIR="./sources/"    # Install Directory
+TIME_OUT="10"           # Connection timeout
+MAX_TIMEOUT="300"       # Full curl timeout
+SUCCESS_URLS=()         # Array of urls that connected successfully
 USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"
 
 load_repos() {
-    # Load the textfile of repos to array
     while IFS= read -r line; do
         if [[ "$line" == \#* ]] || [[ -z "$line" ]]; then
             :
@@ -18,12 +17,22 @@ load_repos() {
             REPOS+=("$line")
         fi
     done < "$REPO_LIST"
+
+    local repo_num=${#REPOS[@]}
+    local repo_prompt="repo"
+
+    if [ "$repo_num" -gt 1 ]; then
+        repo_prompt="${repo_prompt}s"
+    fi
+
+    echo -e "Loaded repository list [$repo_num $repo_prompt] to memory..."
 }
 
 pkg_search() {
     # Search for a single package
-    # Param1: Name of package in string form
     local pkg=$1
+
+    echo "Searching for $pkg..."
 
     for repo in "${REPOS[@]}"; do
         path=$(curl -fsSL "$repo" --connect-timeout "$TIME_OUT" \
@@ -33,22 +42,39 @@ pkg_search() {
 
         if [ -n "$path" ]; then
             SUCCESS_URLS+=("$repo$path")
-            echo -e "${SUCCESS_URLS[@]} ... [FOUND]"
+            echo -e "$repo$path ... [FOUND]"
         else
-            echo -e "${repo}${path} ... [NOT FOUND!]"
+            echo -e "$repo ... [NOT FOUND]"
         fi
     done
 
     # Ask download to do it's job
-    download_pkg "$path"
+    if ! file_exists "$path"; then
+        download_pkg "$path"
+    fi
+}
+
+file_exists() {
+    # Check if a package has already been downloaded
+    name=$1
+    full_file=$(realpath "$PKG_DIR/$name")
+
+    if [[ ! -f "$full_file" ]]; then
+        echo -e "  Package [$name] does not exist in: $PKG_DIR"
+        return 1
+    else
+        file_size_bytes=$(wc -c < "$full_file")
+        file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
+        echo -e "Package [$name] already exists in: $PKG_DIR\n  Size: $file_size MB\n  Location: $full_file"
+        return 0
+    fi
 }
 
 download_pkg() {
     # Download a single package
-    # Param1: The name of the file
-    # Note: If the download passes the timeout it tries the next successful link 
-    name=$1
-    idx=0
+    # Note: If the download passes the timeout it tries the next successful link
+    local name=$1
+    local idx=0
 
     for pkg_url in "${SUCCESS_URLS[@]}"; do
         echo -e "Downloading: $name\n  From: $pkg_url"
@@ -57,7 +83,7 @@ download_pkg() {
             -A "$USER_AGENT" \
             -o "$PKG_DIR/$name" \
             --max-time "$MAX_TIMEOUT"; then
-            
+
             success "$name"
             return 0
         else
@@ -68,7 +94,7 @@ download_pkg() {
             clean_up "$name"
             ((idx++))
 
-            if [ "$idx" -eq "$((${#SUCCESS_URLS} - 1))" ]; then
+            if [ "$idx" -eq "${#SUCCESS_URLS[@]}" ]; then
                 failure "$name"
             fi
         fi
@@ -92,17 +118,20 @@ failure() {
 }
 
 success() {
-    # Tell the user it's been downloaded successfully!
-    # Param1: Full name of the program
     name=$1
-    echo -e "Successfully downloaded $name!\n  Location: $(realpath "$PKG_DIR/$name")"
+    full_file=$(realpath "$PKG_DIR/$name")
+    file_size_bytes=$(wc -c < "$full_file")
+    file_size=$(awk "BEGIN {printf \"%.2f\", $file_size_bytes / 1048576}")
+
+    prompt="Successfully downloaded $name!\n"
+    prompt+="  Size: $file_size MB\n"
+    prompt+="  Location: $full_file"
+    echo -e "$prompt"
     exit 0
 }
 
 main() {
-    # Initialize the Package Downloader
-    # Param1: The name of the package
-    local name="$1"
+    local name="$1"     # Name of the package
 
     [[ ! -d "$PKG_DIR" ]] && { mkdir -pv "$PKG_DIR"; }
     [[ -z "$name" ]] && { echo "Usage: spkg <package>"; return 1; }
@@ -114,10 +143,7 @@ main() {
         exit 1
     fi
 
-    load_repos "$REPO_LIST"
-    echo -e "Repository list [${#REPOS[@]}] loaded to memory..."
-
-    echo "Searching for $name..."
+    load_repos
     pkg_search "$name"
 }
 
